### ISSUE TITLE
NPGTitles:DisplayOrder

### ISSUE THREAD

**Issue by steads** [american-art/npg#19]
DisplayOrder: This is a system implementation instruction and as such has no need for a mapping. However if the meaning in this field is important outside the system then additional instances of E35 Title should be instantiated. For example:-
S/NPG.90.31     ->P102 E35 {Ruth Stanley Farnam}
                ->P102 E35 {A Nation At Bay}
                        ->P102 E35 {Ruth Stanley Farnam: A Nation At Bay}
Note that I have chosen to use “: “ to separate the two Titles as I concatenate them but any characters could be used. It might also be that the concatenated version is no longer considered an E35 Title in which case you could move up to an E41 Appellation. In this case the correct property link would be P1 is identified by (identifies).

**Comment by si-npg** [comment]
Title Display Order is very important, as it determines which title displays when only one title is included. If all titles are included, it does also act as a sort of ranking in terms of relevance.

**Comment by rhao** [comment]
I'm not totally sure how to implement the : concatenation, because each transform seems to apply to that row only, but in the data, the primary and secondary titles are split into 2 rows, and are only identified as referring to the same object because of the ObjectID.

I adapted your suggestion slightly, so let me know if it makes sense (it might not). I have 2 E35_Title instances coming from E22 (representing PrimaryTitle and SecondaryTitle). Each E53_Title has 2 E55_Type instances: 1) TitleType = "Primary Title" or "Secondary Title", and 2) "Not Translatable". So this way, I still tied both titles to E22 with P102, but I also added a second E55_Type to specify the display order, instead of having the third concatenation title.

Maybe the smarter way would be to use E41_Appellation, but I'm not totally sure what an appellation is, so was trying to find an alternate solution.
