### ISSUE TITLE
NPGExhibitionObjXrefs

### ISSUE THREAD

**Issue by steads** [american-art/npg#20]
Overall each row in this table constitutes an instance of the property linking the object (an instance of E22 Man-Made Object) to the exhibition (an instance of E7 Activity). In the mapping the property used is P12 _occurred in the presence of (was present at)_. I think the stronger statement P16 _used specific object (was used for)_ could be used as the record is not just that they were present in the same room but actually formed part of the exhibit. Thus:-
E22     ->P16i ->E7 [Exhibition]
    ->P16.1 ->E55 {Exhibit}

**Comment by VladimirAlexiev** [comment]
Agree about `P16 used specific object` ... though this also implies `<exibition> P15 was influenced by <object>`.

About P16.1: #5 says to put `P2_has_type aat:300054766; # exhibition (event)` on every Exhibition, which means more or less the same (all these objects at exhibition are exhibits), but avoids the difficulty of representing P16.1.

**Comment by steads** [comment]
A] Having an object in an exhibition that doesn't influence the exhibition would be impossible!! P15 is the weak general case and P16 the strong "must have" case.
B] There is a huge difference between saying that an activity is an exhibition and saying that a particular object was an exhibit in the exhibition. Otherwise how do I track other things with different roles in the exhibition (like cases and monitoring equipment)?

**Comment by VladimirAlexiev** [comment]
But there are no other things at these exhibitions.
Can you show some turtle for P16.1?

**Comment by steads** [comment]
As I said previously the cases, frames and other exhibition staging and the instrumentation used to monitor the environment are examples of other things that have different roles in the exhibit. These might be integrated from other museum and conservation systems.

I do not do turtle(s)!

Try looking at the reference to using intermediary nodes in http://www.cidoc-crm.org/docs/31st-meeting-presentations/CRM_FOL_CM_part_1.pdf on page 20 Heading: Meta-properties

**Comment by VladimirAlexiev** [comment]
There's no data about cases, frames etc in this excel. And the generated Exhibition URLs are local to NPG, so no extra data about them can possibly come from other AAC museums.

**Comment by steads** [comment]
What about other sources from within the museum like for instance exhibition management systems and conservation records. Regardless you are missing the point, breaking the semantics and saying something that is not true makes future proofing the data a problem. Smashing things into holes that are not the right shape is why there are so many problems with data integration already.

**Comment by VladimirAlexiev** [comment]
- as I said, there's no extra data as you describe. I'm currently working with JP Getty Museum and they _do_ have cases, frames etc in their collection management system (which is also an inventory management system), but they are explicitly _not_ exporting this to LOD since it 
- I am not saying something that is not true: these events are indeed Exhibitions, and so how am I "breaking the semantics"? You are saying that is not enough (and we should add that each object is an Exhibit), referring to some potential future data.
- The modeling that you suggest corresponds to sec 3.1 (p.8) of my paper "Types and Annotations for CIDOC CRM Properties" http://vladimiralexiev.github.io/pubs/Alexiev2012-CRM-Properties.pdf. But it is one of the most expensive ways, since it doubles the number of classes and triples the number of property types. There are better ways to attach  type to a relation.

**Comment by steads** [comment]
You seem to be working in a "Closed World" where all possible states are already known. The CRM SIG champions "Open World" solutions as we do not believe that all possible states can be known. For simplicity in your engineering solution you may decide to go "Closed World". This would not be our preferred solution.

**Comment by VladimirAlexiev** [comment]
-> JPGM are not exporting non-art-objects (cases etc) to LOD since it does not and never will be of public interest.

**Comment by si-npg** [comment]
NPG does include on our database some exhibition objects that we refer to as "exhibition elements"--equipment, copy photos, etc. I did not include them for the reasons discussed above.

**Comment by VladimirAlexiev** [comment]
So it seems that "museums won't publish LOD about cases and similar appurtenances" is a safe assumption.
My proposal is to map this to:

``` turtle
<object/123> crm:P16i_was_used_for <exhibition/456>.
<exhibition/456> a crm:E7_Activity;
  crm:P2_has_type aat:300054766; # exhibition
  crm:P14_carried_out_by ... # if you have info who organized it
```

**Comment by steads** [comment]
I find it hard to reconcile a Linked Open Data world view and the rather myopic "the public" are not "interested" in this. One of the great things about this project is the potential for broad range of reuse of the rich data outside the primary use case of art discovery/browsing. So linking to name parts to enable name studies, publishing of case and staging data to enable conservation science and exhibition staging research are all great opportunities to broaden the use and potential for "Linking" to other disciplines and research scenarios. Please take the opportunity to publish as much as possible with it's full semantic richness exposed.

**Comment by rhao** [comment]
I'm not quite sure what the consensus was on this. I mapped it according to the discussion in #24 (shown below) - let me know if this is not okay. 

```
_:the_object a crm:E22_Man-Made_Object.

_the_usage a crmpc:PC16_used_specific_object;
  crmpc:P01_has_domain _:the_object;
```

**Comment by VladimirAlexiev** [comment]
What a mess.
@azaroth42 what do you think?

**Comment by azaroth42** [comment]
I agree with @VladimirAlexiev's August 3rd mapping.  If there is a different, more specific, relationship between the Object and the Activity, then there should be a different predicate to make that distinction.
Until there are situations where anyone wants to make that distinction, p16 seems perfectly fine. When there's a need to make the distinction, we can use a predicate to distinguish that the stand was used to support the activity rather than as the focus of the activity.

I disagree with @steads that publishing Absolutely Everything in as much detail as possible is a good idea. As philosophical completeness approaches 100%, usability approaches 0%.
