### ISSUE TITLE
NPGConstituents: use global name field types

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/npg#46]
Currently the mapping uses local types for name parts, eg `<http://americanartcollaborative.org/npg/thesauri/nametype/lastname>`. These cannot be used across collections. As discussed at the Recon workshop, it's better to use global thesauri, eg AAT. Use this mapping:
- title: aat:300404661 or prefix: aat:300404845
- first: aat:300404651
- middle: aat:300404654
- last: aat:300404652
- suffix: aat:300404662

**Comment by azaroth42** [comment]
What's the advantage in reifying here? Something simpler like schema:givenName / schema:familyName would accomplish the same result with few resources created.

**Comment by VladimirAlexiev** [comment]
schema has givenName, familyName, honorificPrefix, honorificSuffix. Just doesn't have middleName (instead, schema:additionalName is also used for middle).

I like the suggestion to use Schema for this, but it's not very CRM-y. @steads, what do you think?

**Comment by steads** [comment]
Do what you like. If you intend to make is searchable as part of a CRM environment then this will not fit.

**Comment by workergnome** [comment]
I think it's important to maintain the local terms for things, unless the institution has made a conscious decision to internally use another vocabulary for their terms.

I also think there is value in reifying things, if only to maintain attribution and authority.  I also think there is value in maintaining the CRM mappings of things—I'm not opposed to there being BOTH schema links and CRM modeling, or there being inferable mappings that are computed from the data.

My suggestion might be to continue to use local terms (because there is a local term, and we should respect that), but perhaps map that local term using `skos:broadMatch` or `skos:closeMatch` to a globally recognized term.  That lets the browse app aggregate the data, but maintains the sanctity of the data provided.

Something like:

``` turtle
_:actor crm:P131_is_identified_by _:actor_name .
_:actor_name a crm:E82_Actor_Appellation;
     crm:p106_is_composed_of _:name_part .
_:name_part a crm:E82_Actor_Appellation ;
        crm:p2_has_type institution:first_name_type .
        rdfs:label "John" .
institution:first_name_type a crm:E55_type ;
        skos:broadMatch aat:300404651.
```

and we could easily and without breaking anything also add the triples

``` turtle
_:actor schema:givenName "John"  ;
  foaf:givenName "John" .
```

and

``` turtle
_:name_part crm:P3_has_note "John" .
```

Which give us both improved compatibility with the CRM and an easy path for people who don't want to go the whole CRM route.

**Comment by VladimirAlexiev** [comment]
- Duplicating info is of course an option, but eg Getty have shied away from this.
- Provenance: I would normally agree, but even if we decide to emit provenance info about persons (which the current mapping does not), it's doubtful that would be done at the level of name parts
- About local terms: there are no local terms maintained as a separate artifact. There are just columns in a table. This is the first time the institutions map their data to values to be used in P2_has_type, so they may as well use the same concept.
- Finally, let's not forget @edgartdata's suggestion to just get rid of the name parts. See the table in #39, the parsing is quite naive and some of the broken-up parts are ridiculous.
- the concept of First & Last name is very Western-culture centric
- ULAN doesn't have name parts
- a Full-text index over the full name would do better

**Comment by VladimirAlexiev** [comment]
> searchable as part of a CRM environment

I created the first CRM Fundamental Relations search (in ResearchSpace), but I am not aware of any CRM search to use name parts.
IMHO the only reasonable way to search for names is Full-Text Search.

**Comment by steads** [comment]
Name parts would be useful if you want to study the names themselves. So making them available will make the data set useful in other ways than just looking up artworks. Therefore my preference would be to provide them where they are real, so as @VladimirAlexiev says they need to be cleaned of the nonsensical false parts.

**Comment by VladimirAlexiev** [comment]
Ok, so this depends on the decision to be taken in #39 after we see the cleaned up data set. Cheers!
