### ISSUE TITLE
NPGObjConXrefs: skip displayed=0

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/npg#48]
133 of 263k records (0.05%) have displayed=0. From my work with JP Getty Museum (who also use TMS), this field indicates the record should not be published.
So use this to filter out such records

**Comment by VladimirAlexiev** [comment]
@si-npg, @kateblanch: New export: 218 of 42k records have displayed=0

**Comment by si-npg** [comment]
These constituents are not private, they don't display in order to make the display record less confusing. If the artst is a partnership, like Southworth & Hawes, we enter both the partnership and the individual artists as well--so three constituents--but we only display the partnership name. (I know other museums handle partnerships differently.) Beides partnerhips, there are just a few other instances of sitters/artists not displaying, and I'll have to verify the reason for each.

**Comment by VladimirAlexiev** [comment]
If the decision is to keep them, please close this and #35 (both do not require mapping changes)
