### ISSUE TITLE
NPGRefObjXrefs

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/npg#55]
Important bibliographic info, having these fields:
- ObjectID
- RefObjXrefID
- ReferenceID
- Illustrated
- Remarks
- PageNumber
- CatalogueNumber
- FigureNumber

@kateblanch @si-npg: please also provide NPGReferences, since this table is not useful without that one.
- What is Illustrated?

**Comment by si-npg** [comment]
Is "npgbibreferences" not included?

**Comment by VladimirAlexiev** [comment]
Ah, I missed it because the file name is lowercase.
**npgbibreferences** has fields:
- ReferenceID
- Format
- Title
- SubTitle
- PlacePublished
- YearPublished

What is Illustrated?

**Comment by VladimirAlexiev** [comment]
@steds @workergnome @azaroth42 How do you like this modeling?

``` turtle
<npg/object/(ObjectID)> crm:P70i_is_documented_in <npg/object/(ObjectID)/reference/(RefObjXrefID)>.
<npg/object/(ObjectID)/reference/(RefObjXrefID)> a crm:E31_Document;
  crm:P106i_forms_part_of <npg/reference/(ReferenceID)>;
  crm:P3_has_note "(Remarks)";
  crm:P1_is_identified_by <npg/object/(ObjectID)/reference/(RefObjXrefID)/page>.

<npg/object/(ObjectID)/reference/(RefObjXrefID)/page> a crm:E42_Identifier;
  puml:label "similar for CatalogueNumber and FigureNumber";
  crm:P2_has_type <thesaurus/identifier/pageNumber>;
  crm:P3_has_note "(PageNumber)".

<npg/reference/(ReferenceID)> a crm:E31_Document, frbroo:F24_Publication_Expression;
  puml:label "TODO emit ReferenceID as crm:E42_Identifier?";
  crm:P2_has_type <thesaurus/reference/(Format)>;
  crm:P102_has_title <npg/reference/(ReferenceID)/title>, <npg/reference/(ReferenceID)/subtitle>;
  frbroo:R24i_was_created_through <npg/reference/(ReferenceID)/publication>.

<npg/reference/(ReferenceID)/title> a crm:E35_Title;
  crm:P2_has_type aat:300195168.

<npg/reference/(ReferenceID)/subtitle> a crm:E35_Title;
  crm:P2_has_type aat:NEW.

<npg/reference/(ReferenceID)/publication> a frbroo:F30_Publication_Event;
  crm:P7_took_place_at <npg/reference/(ReferenceID)/publication/place>;
  crm:P4_has_time-span <npg/reference/(ReferenceID)/publication/date>.

<npg/reference/(ReferenceID)/publication/place> a crm:E53_Place;
  crm:P87_is_identified_by <npg/reference/(ReferenceID)/publication/place/name>.

<npg/reference/(ReferenceID)/publication/place/name> a crm:E44_Place_Appellation;
  crm:P3_has_note "(PlacePublished)".

<npg/reference/(ReferenceID)/publication/date> a crm:E52_Time-Span;
  crm:P82_at_some_time_within "(YearPublished)"^^xsd:gYear.
```

![image](https://cloud.githubusercontent.com/assets/536250/17579472/a411f87a-5f9e-11e6-8071-367d04f4ebbc.png)

**Comment by azaroth42** [comment]
I think using CRM for modeling bibliographic references is using a sledgehammer to drive in a screw, when there's a whole toolbox full of different screwdrivers available. It's just the wrong tool for the job.

**Comment by caknoblock** [comment]
We discussed which ontology to use to model bibliographic data at the AAC meeting we held at the Getty and after a lengthy discussion we agreed to use CRM.  We don’t have that much bibliographic data and I don’t think it plays an important role in the browse application, so let’s move on to more important issues.

**Comment by azaroth42** [comment]
Okay, if it's not important for AAC, then I won't stand in the way of getting something out there.  But please let's not say it's a best practice to do this.

That said, we (The Getty) are not going to do it the wrong way like this. We _do_ have a lot of bibliographic information, split across several different systems and all the different programs. You can imagine that telling the Research Institute that it has to use a terrible CRM mapping rather than established Library Linked Data ontologies is not going to go down well, particularly when the vendor is working on LOD straight from the catalog system.

For example:
- The Museum objects have extensive bibliographies: (e.g. http://www.getty.edu/art/collection/objects/882/rembrandt-harmensz-van-rijn-the-abduction-of-europa-dutch-1632/ and scroll down, click on bibliography tab)
- The vocabularies have bibliographic source information about where the terms were found
- We have a full library of books and journals at the GRI! http://primo.getty.edu/primo_library/libweb/action/search.do?vid=GRI
- We maintain the BHA: http://www.getty.edu/research/tools/bha/
- And the AATA: http://aata.getty.edu/Home

**Comment by workergnome** [comment]
Definitely interested in a best practice here.  Being able to link to the works referenced here through WorldCat would be a fantastic feature for the Browse application, and would really showcase the potential of Linked Data.

I don't have a strong opinion on the mapping—I'm still trying to figure out Best Practices for this from my librarian friends, but I think finding the correct entity to get to via CIDOC, and then link out to an external reference for the full details would be great.  

I think, much like Actors, it's probably up to the institutions to help us understand how much of the data they have for the reference is institution-specific and would be lost if not modeled, and how much of the data is there because they don't have a way to implement Linked Data, and so they have to duplicate data from the true primary source.

**Comment by VladimirAlexiev** [comment]
@azaroth42 Which is the established bib ontology in your opinion? Maybe a year ago I asked a question on stackoverflow (or was it answers.semanticweb.org) titled "War of the bibliographic ontologies" :-) Would be nice if you post there. 
Also we had an impromptu vote re DBpedia Citations at https://github.com/dbpedia/mappings-tracker/issues/79

The various alternatives include BIBO, RDAinfo, CITO and family, SchemaBibEx, BibFrame, FRBRoo.
- I like SchemaBibEx (bib.schema.org) but haven't tried it on a big/real dataset. Eg AATA has many weird and wonderful fields (eg Figure number)
- for GVP we used BIBO but GVP has only a couple fields for sources
- there were plans to map AATA to FRBRoo. 
- I contributed some AATA analysis here: https://share.getty.edu/display/ITSLODAATA/AATA+Notes (June 2016)
