### ISSUE TITLE
NPGDimsParsedUpdate2May no unit specified

### ISSUE THREAD

**Issue by rhao** [american-art/npg#59]
The NPGDimsParsedUpdate2May dataset has width, height, and depth measurements, but doesn't specify what unit. I'm simply going to map the data that's there, but measurement unit might be a column that's worth adding. If the unit data is added, let me know because I'll have to update the model to include it.

**Comment by si-npg** [comment]
I'm attaching a new file that includes both Display Dimensions (for clarification purposes) and Primary and Secondary Dimension Units. I think only the Primary Unit is needed, since I don't see the Secondary Unit dimensions in the table...? I exported the units as IDs and manually changed them to text, which I assume is better?
[NPGDimsParsedUpdate1Nov.xlsx](https://github.com/american-art/npg/files/564311/NPGDimsParsedUpdate1Nov.xlsx)

**Comment by bsnikhila** [comment]
The new file is now used.
