### ISSUE TITLE
Newer export available?

### ISSUE THREAD

**Issue by azaroth42** [american-art/npg#8]
I believe that there is a newer export available, that (following the Princeton export) has dimensions separated out into different fields for ease of processing? Could that export be made public via github?

**Comment by si-npg** [comment]
YES! I did a second export it in April and sent it to Craig Knoblock via Dropbox in June. I e-mailed him earlier today asking for help making it available here. (I was never able to get a pull request to work.) It contains not only parsed dims but also indexed values for medium and support and some provenance data. Most importantly, the constituent spreadsheet is 8-9 times smaller because it excludes nearly 93,000 constituents that aren't even sitters or artists for our object records!
